baseURL = 'https://dushyant03.github.io/blogness/'
languageCode = 'en-us'
title = 'The Blogness Monster'
theme = 'm10c'

[params]
  author = "Dushyant Chakravorty"
  description = "A blog about all things I like."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/dushyant03"
