baseURL = 'https://dushyant03.github.io/blogness/'
languageCode = 'en-us'
title = 'The Blogness'
theme = 'soho'

summarylength = 10
enableEmoji = true

[params]
author = "Dushyant Chakravorty"
description = "My Blog"
profilePicture = "images/avatar.jpg"

  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/dushyant-chakravorty-a9199759/"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/dushyant03?tab=repositories"

[menu]

  [[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 300
  url = "/about/"
