baseURL = 'https://dushyant03.github.io/blogness/'
languageCode = 'en-us'
title = "The Blogness"
 theme = "color-your-world"
#theme = "nightfall"


[params]

  footerText = [ "Author: Dushyant Chakravorty" ]

[languages]

  [languages.en]
  
    languageName = "English"

    [languages.en.menu]
      
      [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "about/"

      [[languages.en.menu.main]]
        name = "Posts"
        weight = 2
        url = "posts/"

